language: python
python:
  - "3.7"
  - "3.7-dev" # 3.7 development branch
install:
  - "pip install pipenv"
  - "pipenv install"
script: "python -m pytest "
after_success:
  - "python-codacy-coverage -r coverage.xml"
